# Generated by Django 3.2.18 on 2023-02-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('orders_amount', models.IntegerField(verbose_name='Количество заявок')),
                ('response_time', models.IntegerField(verbose_name='Время ответа (в часах)')),
                ('order_cost', models.IntegerField(verbose_name='Стоимость выполнения одной заявки')),
                ('active', models.BooleanField(db_index=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
    ]
