# Generated by Django 3.2.18 on 2023-02-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orderapp', '0007_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Статистика по заявке',
                'verbose_name_plural': 'Статистика по заявкам',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orderapp.order',),
        ),
    ]
