# Generated by Django 3.2.18 on 2023-02-22 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_auto_20230223_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='orderapp.client', verbose_name='Подано клиентом'),
        ),
        migrations.AlterField(
            model_name='client',
            name='active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='orderapp.manager', verbose_name='Ответственный менеджер'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новое'), ('WOR', 'В работе'), ('CLO', 'Закрыто')], db_index=True, default='NEW', max_length=3, verbose_name='Статус'),
        ),
    ]
