# Generated by Django 3.2.18 on 2023-02-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0005_auto_20230223_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='resume',
            field=models.TextField(blank=True, verbose_name='Резюме'),
        ),
    ]
