# Generated by Django 3.2.18 on 2023-02-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0006_contractor_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('WOR', 'В работе'), ('FIN', 'Завершен'), ('OVE', 'Просрочен')], db_index=True, default='NEW', max_length=3, verbose_name='Статус'),
        ),
    ]
