# Generated by Django 3.2.18 on 2023-02-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credentials',
            field=models.TextField(blank=True, verbose_name='Данные для админки'),
        ),
    ]
