# Generated by Django 3.2.18 on 2023-02-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0010_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='description',
            new_name='text',
        ),
    ]
