from enum import Enum


class ContractorState(Enum):
    ACCOUNT_ON_REVIEW = "ACCOUNT_ON_REVIEW"
    RESUME_REQUEST = "RESUME_REQUEST"
    HOME = "HOME"

    AVAILABLE_ORDERS = "AVAILABLE_ORDERS"
    AVAILABLE_ORDER_DETAIL = "AVAILABLE_ORDER_DETAIL"
    TIME_ESTIMATE_REQUEST = "TIME_ESTIMATE_REQUEST"

    ORDERS = "ORDERS"
    ORDER_DETAIL = "ORDER_DETAIL"
    ORDER_REPORT_REQUEST = "ORDER_REPORT_REQUEST"
    ORDER_COMPLETE_CONFIRMATION = "ORDER_COMPLETE_CONFIRMATION"

    STATISTICS = "STATISTICS"
